### ISSUE TITLE
Calculating co-occurrences

### ISSUE THREAD

**Issue by YanXuHappygela** [Microsoft/Product-Recommendations#11]
How do you define the co-occurrences of items? The items with the same timestamps in the usage file are identified in the same transaction, or the within certain time range?

**Comment by natinimni** [comment]
It depends on whether you set the training parameter ‘cooccurrenceUnit’ to ‘User’ or ‘Timestamp’:
 
“*Indicates how to group usage events before counting co-occurrences. A 'User' cooccurrence unit will consider all items purchased by the same user as occurring together in the same session. A 'Timestamp' cooccurrence unit will consider all items purchased by the same user in the same time as occurring together in the same session.*” (see: [Model Training Parameters Schema](https://github.com/Microsoft/Product-Recommendations/blob/master/doc/api-reference.md#model-training-parameters-schema)).

You can also learn more about the SAR algorithm in this doc: [SAR](https://github.com/Microsoft/Product-Recommendations/blob/master/doc/sar.md).

I hope this answers your question.
