### ISSUE TITLE
Evaluation process and results

### ISSUE THREAD

**Issue by YanXuHappygela** [Microsoft/Product-Recommendations#15]
For the evaluation, the recommendation is user based, right? Is it evaluated line by line in the evaluation file or first group the items by timestamp/user id and match with the recommendation results?
I have a dataset that has items fewer than 100, customers over 1M. I'm wondering whether I can access all the output for the evaluation file?
Thank you so much!

**Comment by abhi1509** [comment]
Yes, for evaluations, the recommendations are user based.
The evaluation users are grouped based on Id. Time stamp is not used for grouping. Also only those evaluation users are scored, which have atleast one even in the usage file.

Currently the code doesn't write the scored items from evaluation. However, you can modify 
https://github.com/Microsoft/Product-Recommendations/blob/master/source/Recommendations.Core/Evaluate/ModelEvaluator.cs: ScoreTestUsers function to do so.
