### ISSUE TITLE
Input data validation tool

### ISSUE THREAD

**Issue by c-w** [microsoft/Product-Recommendations#20]
We recently tried to deploy this solution with a partner, using the sample C# console app client.

We faced several issues massaging the partner's data into the correct format for the SAR service and found the error messages from the service not extremely helpful at tracking down data issues. For example, the input data looks like CSV but doesn't seem to support standard CSV-encoded commas in columns.

As such, it would be super valuable to have a little tool that verifies that the input data is in the correct format for the SAR service so that data issues can be precisely located and fixed instead of trying to run the model and having to wait for a while until the bad data is hit which greatly slows down iteration speed.

**Comment by natinimni** [comment]
Hi @c-w ,
The project uses .NET's "TextFieldParser" class to parse the input CSV files (see [UsageEventsFilesParser](https://github.com/Microsoft/Product-Recommendations/blob/master/source/Recommendations.Core/Parsing/UsageEventsFilesParser.cs) for example).

I should be straight forward to create such a validation tool in C# by referencing the [Recommendations.Core](https://github.com/Microsoft/Product-Recommendations/tree/master/source/Recommendations.Core) project and calling the **UsageEventsFilesParser** class (you might need to change it from being 'internal' to 'public', depending on your implementation). 

If you do find a bad pattern use or a way to make the parsing support more standard escaping etc., we would truly appreciate any contributions back to this project!    

I hope this helps,
Nati
