### ISSUE TITLE
Incremental training of SAR model

### ISSUE THREAD

**Issue by c-w** [Microsoft/Product-Recommendations#21]
Training over large data-sets takes quite a while, even on the highest deployment plan. Is there a way to incrementally train the SAR model as new usage data becomes available?

**Comment by natinimni** [comment]
Hi @c-w ,
Unfortunately the core SAR algorithm doesn’t support papalism or incremental builds.
I am not sure if this could apply to your data, but some users improve the performance by creating more than one model, where their items are split into distinct categories that would never be cross-recommended anyway, for example kids vs. adults sized cloths. 
I hope this helps.
Nati

**Comment by c-w** [comment]
Hi @natinimni. Splitting the recommendations over multiple models is a great idea. Thanks for the suggestion!
