### ISSUE TITLE
Suggestion - Support for Azure Append Blob for catalog file

### ISSUE THREAD

**Issue by khrubes** [microsoft/Product-Recommendations#24]
I am developing a script to add new products to my catalog file in my Azure blob container. 
The blob type for my catalog file is an Append Blob, because in C# it supports [appending new lines to an existing file](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudappendblob.appendtextasync?view=azure-dotnet). This is much simpler than using the standard block blob's [write operation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblockblob.uploadtextasync?view=azure-dotnet) which overwrites the previous entries. 

When I try to train my model with my catalog file as type append blob, I get the error
 'System.Exception: Failed downloading training files from storage. Model id: 198d7cdf-818c-4fd5-a8b3-c8c636cdabd8 ---> Microsoft.WindowsAzure.Storage.StorageException: Blob type of the blob reference doesn't match blob type of the blob. ---> System.InvalidOperationException: Blob type of the blob reference doesn't match blob type of the blob.
 at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.UpdateAfterFetchAttributes(BlobAttributes blobAttributes, HttpWebResponse response)
 at Microsoft.WindowsAzure.Storage.Blob.CloudBlob

Is there a chance append blob's will be supported in the future?

**Comment by natinimni** [comment]
Sounds reasonable. Feel free to support append blobs and send a PR – we could approve and re-publish the solution template with that change.  

Thanks,
Nati
