### ISSUE TITLE
Filtering and boosting recommendations 

### ISSUE THREAD

**Issue by prateekrastogi** [Microsoft/Product-Recommendations#28]
Hi,

Are there any ways to filter and boost recommendations according to particular properties of items such as view count, non-linear boundaried genres etc? Also, i would like to know the future roadmap of this project as envisioned internally in Microsoft.

Thank you.

**Comment by natinimni** [comment]
Hi @prateekrastogi, 
Unfortunately there is no built-in way to filter\boost recommendations.
As for the road map for this project - this project was created as a "self hosting" solution following the deprecation of the managed Cognitive Service's Recommendation API service. Currently, and for the foreseeable future, this project is offered as is.  

Thanks,
Nati

**Comment by prateekrastogi** [comment]
@natinimni Thank you for resolving my queries.
