### ISSUE TITLE
Question - How can I integrate multiple solutions on one Azure Web App.

### ISSUE THREAD

**Issue by maiko-okawa** [Microsoft/Product-Recommendations#32]
Hi.

I tried ARM deployment. It's so useful.
By the way, I'd like to integrate multiple solutions on one Azure WebApp, what should I do?

I manage 3 solutions and update each model everyday, these are running on each WebApp.
I'd like to integrate WebApp into one, because the price of WebApp is expensive.

I do not want to mix models in one solution, because these models are using in completely different use cases.

Do you have any ideas?

Thank you.

**Comment by maiko-okawa** [comment]
@natinimni

Thank you for your reply.
Now our mobile applications are using each default URL.
Okay, I look for the way to change API management's URL programmatically every day for referring their id.

Thank you.

**Comment by natinimni** [comment]
The other option is to modify the solution code to support more than one "default" model, something like allowing "friendly model name" that could be assigned to some concrete model id and changed later, similar to the way "default" model works. I believe this should be a relatively simple change to the code.

Thanks,
Nati

**Comment by maiko-okawa** [comment]
Thank you for your advice. 

I am still investigating at the moment, however, maybe I can change the API Management settings programmatically.

I also considered modifying the code but since I am already using API management, I think the modifying API management would be the best approach. 

Your advice was very helpful. 

Thank you.
