### ISSUE TITLE
Question: is Product Recommendations a fit for us?

### ISSUE THREAD

**Issue by shaulbehr** [microsoft/Product-Recommendations#34]
Hi,
I'm the system architect for a company that produces a literacy product for students reading in schools. The product is basically an e-reader, in which the students can select and read books in class, and we've basically gamified the experience while collecting a ton of data points.
The problem we're trying to solve now is that students are spending too much time browsing through the library of available books; we want to minimize their browsing time and maximize their reading time. 
So we figure Product Recommendations might be the way to go. A few questions, though:

1. Not all students have access to the same libraries. Even within the same school, some students might not have rights to books that other students can see. Does Product Recommendations have the facility to limit recommendations to the books to which they have access?
2. Does Product Recommendations allow including factors like "Trending", i.e. what other users are currently reading? We do want to show books that the student is likely to be interested in, because of topic, genre, author, etc., but we also want to expose them to other books that are popular, new releases, etc.
3. Can we factor in other users' ratings, both positive and negative? We have a lot of data of which books our users like and don't like, and that could be a factor in the recommendations.
4. We also have a metric called Lexile, which is a measure of reading level. We try to encourage students to read books with a Lexile rating within 200 points of their own Lexile score. Can we incorporate this into the algorithm?

TIA for your help!

**Comment by natinimni** [comment]
Hello shaulbehr, apologies for the delayed reply. 

Sounds like a cool project! 
In general it seem like this project could suit most if not all of your requirements, albeit if would require some integration with your system. Please find answers below -

1. There is no built-in filtering mechanism. If the access restriction have commonality (as oppose to each student having its own unique access profile), you could train several separate models, each with a subset of books catalog corresponding to the allowed books in that group. Of course you would still have to map each student to its model, but it seems that the students are already authenticated into your system, so perhaps keeping that record (model id for each student) is possible?
My other suggestion is to implement “post filtering” on top of the recommendation service, that will get a large number of recommendations and then filter according to the student access permissions. For example it will ask for 100 recommendation items and filter those to get relevant 10 that will be presented to the student.
2. One way to achieve this is to re-train the recommendation model frequently (daily\weekly) using fresh usage data – this would naturally bump up recently used items, as newly used items are generally higher ranked. 
3. To achieve this, I think there’s one approach you can consider. While models are trained using a catalog and usage-events data that are not changed\updated for the lifetime of the model, one can pass additional usage-events to specific [recommendation request](https://github.com/microsoft/Product-Recommendations/blob/master/doc/api-reference.md#get-personalized-recommendations) (the ‘userId’ could be omitted from these requests) – the algorithm will consider the additional usage-events provided to get more up-to-date\relevant recommendation results (i.e. without retraining the model with these new events). I believe you can use that feature to achieve user ratings – the [schema of these additional usage-events](https://github.com/microsoft/Product-Recommendations/blob/master/doc/api-reference.md#get-recommendations-usage-event) includes a numeric **weight** field that could be negative – modeling the recent students’ ratings (positive or negative) using appropriate weights, might yield the desired results. Does that makes sense? 
4. This seems like a good candidate for separate models (as suggested in # 1) – you could create a separate book catalogs for different Lexile groups, with potentially overlapping Lexile ranges (e.g. 0-200, 100-300, 200-400, or something else that makes sense) and trains a separate model for each such group. When recommendation are collected for a specific student, the relevant model is selected, using their Lexile score.

Let me know if you have any follow up questions, I’ll do my best to answer them.
