### ISSUE TITLE
Is this the Brussels Sprouts booth at the fun fair?

### ISSUE THREAD

**Issue by shaulbehr** [microsoft/Product-Recommendations#35]
There appears to be zero traffic on this repository, nobody posting bugs, nobody asking or answering questions. 
Does anyone in the real world use this product?
Or has Microsoft abandoned this field to AWS and Google?

**Comment by LuisCabrer** [comment]
Hi shaulbehr,
There are some folks using it -- although it is not a high level traffic site.
This is meant to be a template for customers to use. It's up to you to consume it. ... but yes, it is given to you "AS IS". It's up to you to modify it to meet your particular needs. We hope it is useful though.

That said, in the area of personalization, Microsoft just last month released https://azure.microsoft.com/en-us/services/cognitive-services/personalizer/ 

If you would like to chat with the PM in charge of that service, I can connect you. Thanks!
-Luis Cabrera
