### ISSUE TITLE
Deploy to Azure button results in 'DeploymentFailed' because ''remoteDebuggingVersion' has an invalid value'

### ISSUE THREAD

**Issue by whogben** [microsoft/Product-Recommendations#45]
Attempting to use the deploy to azure link with default values results in an error.

Steps to reproduce:
1) create new azure account
2) sign up for free trial, enter billing etc
3) use "deploy to azure" button at top of this page: https://github.com/microsoft/Product-Recommendations/tree/master/deploy
4) create a resource, accept the terms, and hit "Purchase"

Result is this error:

`{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "BadRequest",
      "message": "{\r\n  \"Code\": \"BadRequest\",\r\n  \"Message\": \"The parameter 'remoteDebuggingVersion' has an invalid value. Details: Supported Versions: VS2017,VS2019.\",\r\n  \"Target\": null,\r\n  \"Details\": [\r\n    {\r\n      \"Message\": \"The parameter 'remoteDebuggingVersion' has an invalid value. Details: Supported Versions: VS2017,VS2019.\"\r\n    },\r\n    {\r\n      \"Code\": \"BadRequest\"\r\n    },\r\n    {\r\n      \"ErrorEntity\": {\r\n        \"ExtendedCode\": \"01033\",\r\n        \"MessageTemplate\": \"The parameter '{0}' has an invalid value. Details: {1}.\",\r\n        \"Parameters\": [\r\n          \"remoteDebuggingVersion\",\r\n          \"Supported Versions: VS2017,VS2019\"\r\n        ],\r\n        \"Code\": \"BadRequest\",\r\n        \"Message\": \"The parameter 'remoteDebuggingVersion' has an invalid value. Details: Supported Versions: VS2017,VS2019.\"\r\n      }\r\n    }\r\n  ],\r\n  \"Innererror\": null\r\n}"
    }
  ]
}`

**Comment by natinimni** [comment]
This is now fixed.
Please make sure to verify that the failed deployment did not leave any unused resources, and delete them as necessary.
