### ISSUE TITLE
Get Item-To-Item Recommendations Filtering by recommendedItemId match

### ISSUE THREAD

**Issue by edqu3** [microsoft/Product-Recommendations#49]
Hi,

Is there to filter out recomendedItemId field by some constraint?

for example.
only return recommendedItemId results ending with character w 
&recommendedItemId=.*w$

https://recommendationstoragews.azurewebsites.net/api/models/default/recommend?userId=00000000-0000-0000-0000-000000000000&recommendationCount=10&recommendedItemId=.*w$

**Comment by natinimni** [comment]
unfortunately there is no such option.
