### ISSUE TITLE
Substitute Products Support

### ISSUE THREAD

**Issue by akblissweb** [Microsoft/Product-Recommendations#5]
I would like to know if it is possible to somehow have alternative products, which may be a better alternative, or have a higher markup, to come up in the results of the recommendation.   These products may or may not be cold, but need to be prioritized over standard recommendations.   

Is this possible somehow using features or would the code here have to be changed.

**Comment by natinimni** [comment]
Unfortunately there is no out of the box “up sale” feature for promoting products, hence the code will have to be changed to support that.
