### ISSUE TITLE
How to train the existing model 

### ISSUE THREAD

**Issue by MaheeTech** [microsoft/Product-Recommendations#55]
I am trying to train the existing model  based on the usage file. There is no api call to train the existing model.....can you please suggest any thing

**Comment by natinimni** [comment]
The can train a new model using the same catalog file but with the new usage file - [Train a New Model](https://github.com/microsoft/Product-Recommendations/blob/master/doc/api-reference.md#train-a-new-model).
The system can have multiple trained models simultaneously, so once you're happy with the new trained model, you may designate it as the "default" model and/or delete the old model.
