### ISSUE TITLE
Deploy on on-premise servers

### ISSUE THREAD

**Issue by Martha-91** [microsoft/Product-Recommendations#56]
Can I deploy this solution on an on-premise server, not on azure cloud?
How can I do that?

**Thanks**

**Comment by natinimni** [comment]
You can clone the repository, build the source code and deploy it anywhere that can run .NET

**Comment by Martha-91** [comment]
> You can clone the repository, build the source code and deploy it anywhere that can run .NET

Thanks @natinimni
