### ISSUE TITLE
catalog file schema best practice when the item has many categories

### ISSUE THREAD

**Issue by AhmedRamadan001** [microsoft/Product-Recommendations#57]
In catalog file schema <Item Id>,<Item Name>,<Item Category>[,<Description>], I think the item category has only one value.
so what is the best practice when the item has many categories?

**Comment by natinimni** [comment]
Catalog items may have [`Features`](https://github.com/microsoft/Product-Recommendations/blob/master/doc/api-reference.md#why-add-features-to-the-catalog), which should [resemble categories](https://github.com/microsoft/Product-Recommendations/blob/master/doc/api-reference.md#features-are-categorical). You can try modeling categories as features and experiment to see if you get satisfactory results.

**Comment by AhmedRamadan001** [comment]
@natinimni  thank you
