### ISSUE TITLE
Taking lot of time when i try to train a model using rest api

### ISSUE THREAD

**Issue by raviranjan20** [Microsoft/Product-Recommendations#8]
Hi,

I am trying to train a model using rest api's call but its taking lot of time though size of usage file is 170 MB.

Request is something like this

headers 
content-type : application/json
x-api-key:*******

Body
{
  "description": "Test_RESTAPIBuild",
  "blobContainerName": "input",
  "catalogFileRelativePath": "Catalog/catalog_sample.csv",
  "usageRelativePath": "Usage/usage_sample.csv",
  "evaluationUsageRelativePath": "Usage",
  "supportThreshold": 5,
  "cooccurrenceUnit": "0",
  "similarityFunction": "Jaccard",
  "enableColdItemPlacement": true,
  "enableColdToColdRecommendations": true,
  "enableUserAffinity": true,
  "enableUserToItemRecommendations": true,
  "allowSeedItemsInRecommendations": true,
  "enableBackfilling": true,
  "decayPeriodInDays": 5
}

what exactly is issue ? I remember when I did through c# application it got trained in seconds.
 
Response I am getting is

 {
        "id": "XXXXXXX-d000-452a-947e-XXXXXXXXXXX",
        "description": "Test_RESTAPIBuild",
        "creationTime": "2018-01-10T10:31:36.0281983Z",
        "modelStatus": "InProgress"
    }

**Comment by natinimni** [comment]
Hi @raviranjan20 
Looking at the used model parameters, specifically on:
{ … 
"usageRelativePath": "Usage/usage_sample.csv",
"evaluationUsageRelativePath": "Usage",
… }

Setting evaluationUsageRelativePath to “Usage” means that all the usage files under the “Usage” folder would be used for evaluation – this includes the actual usage file you used for training, “usage_sample.csv”, as it is too under the “Usage” folder.
If you want to use model evaluation (note that it is optional), you would usually split your usage file to two parts - one part to be used for training (“usageRelativePath”) and the other for testing\evaluation your trained model (“evaluationUsageRelativePath”) – typically the part used for evaluation is much smaller as evaluation is a time consuming process. 

I suggest you should start a new training process while leaving the evaluationUsageRelativePath empty (or simply remove it altogether) – this will train your model much faster (but without evaluation statistics). – make sure to delete the existing model if it’s still “in progress”.
If you would later want to use evaluation, split the usage file as describe above and either set evaluationUsageRelativePath to point to a specific file or to a separate folder containing just evaluation file(s).
Read more about model evaluation here.

I hope this helps!
