### ISSUE TITLE
Use existing App service plan

### ISSUE THREAD

**Issue by hkusulja** [Microsoft/Product-Recommendations#9]
I already have existing Resources groups, and existing one Azure App Service.
I want to deploy this solution and connect to existing Azure services (existing resource group, Existing App Service, existing storage account). But this creates a new blank. I am not able to change Web App to connect to existing Azure App Service later, (same region etc.) because of new limitation.

please make it easier to deploy separately, and to connect to existing azure resources, rather then creating a new ones.

**Comment by natinimni** [comment]
Hi @hkusulja 
Deploying to an existing resource group is not currently possible from the [Cortana Intelligence Gallery](https://gallery.cortanaintelligence.com/Tutorial/Recommendations-Solution) platform, which this solution is hosted on.
However, if you are trying to update an existing deployment, you may try one of the options listed here - [Deployment Instructions](https://github.com/Microsoft/Product-Recommendations/blob/master/doc/deployment-instructions.md#post-deployments)
I hope this helps.

**Comment by hkusulja** [comment]
Thank you for fast response. Ok, so I need to manually create Azure resources and deploy this git repo solution. So After build and publish to Azure web app - I need more documentation about appsetttings etc.

**Comment by natinimni** [comment]
If you are not making any code changes, you could actually use the pre-built package & ARM template to deploy this solution – I believe this would prove to be the easiest way to achieve what you want.
You can find the package here: (https://github.com/Microsoft/Product-Recommendations/blob/master/saw/recommendationswebapp/assets/Recommendations.WebApp.zip)
And the ARM template here: (https://github.com/Microsoft/Product-Recommendations/blob/master/saw/recommendationswebapp/core/arm/resources.json)
